### ISSUE TITLE
EMS Document Generation

### ISSUE THREAD

**Issue by brittanyfriedland** [Open-MBEE/mdk#14]
How do you generate a document (pdf or word) from EMS? Also we don't know how to get our site to appear on EMS..do you have to set a site property for that to work?

**Comment by cinyoung** [comment]
Document generation - we can show you, but here are the steps (you'll need to install docbookgen repository into /opt/local/docbookgen - or reconfigure).
* create a tag
* in sites and documents page, select a snapshot, you'll see buttons for generating the documents

Due to a proliferation of sites, on the sites and documents page, things without "Site Characterizations" are filtered out by default. If you click the eye button in the sites and documents page, all sites are shown.

**Comment by brittanyfriedland** [comment]
Cinyoung,

I do not have a button to generate documents in EMS. I see the buttons that should be there per the user manual, but they are not present on in my installation.

thanks!
